import { ScriptTemplate } from './types';

export const SCRIPT_TEMPLATES: ScriptTemplate[] = [
  // --- File Management ---
  {
    id: 'backup-dir',
    nameKey: 'template_backupDir_name',
    descriptionKey: 'template_backupDir_desc',
    prompt: 'Crie um script robusto que faz backup de um diretório de origem para um diretório de destino. O script deve: aceitar origem e destino como argumentos de linha de comando com flags (-s, -d); criar um arquivo .tar.gz com timestamp no nome (ex: backup-YYYY-MM-DD_HH-MM-SS.tar.gz); verificar se o diretório de origem existe; verificar se o diretório de destino existe e criá-lo se não existir; registrar mensagens de log (info, erro) em um arquivo de log e também na saída padrão.',
    category: 'file',
  },
  {
    id: 'organize-files-by-type',
    nameKey: 'template_organizeFiles_name',
    descriptionKey: 'template_organizeFiles_desc',
    prompt: 'Crie um script para organizar os arquivos em um diretório (ex: Downloads) em subdiretórios com base em seus tipos de arquivo. O script deve: aceitar o diretório a ser organizado como argumento; criar pastas como "Imagens", "Documentos", "Vídeos", "Arquivos"; mover arquivos (.jpg, .png) para "Imagens", (.pdf, .docx) para "Documentos", etc.; lidar com arquivos que já existem no destino para não sobrescrevê-los (adicionando um sufixo).',
    category: 'file',
  },
  {
    id: 'bulk-rename',
    nameKey: 'template_bulkRename_name',
    descriptionKey: 'template_bulkRename_desc',
    prompt: 'Gere um script de renomeação em massa. Ele deve aceitar um diretório, um padrão de busca (regex) e uma string de substituição. Inclua um modo "dry run" (-d) que apenas mostra as alterações sem executá-las. Adicione tratamento de erro para padrões de regex inválidos.',
    category: 'file',
  },
  {
    id: 'find-large-files',
    nameKey: 'template_findLargeFiles_name',
    descriptionKey: 'template_findLargeFiles_desc',
    prompt: 'Crie um script que encontra os 10 maiores arquivos em um diretório e seus subdiretórios. O script deve aceitar o diretório como argumento e exibir uma lista formatada com o tamanho do arquivo (em formato legível, ex: MB, GB) e o caminho completo.',
    category: 'file',
  },
  {
    id: 'deduplicate-files',
    nameKey: 'template_deduplicateFiles_name',
    descriptionKey: 'template_deduplicateFiles_desc',
    prompt: 'Escreva um script que encontra e remove arquivos duplicados em um diretório, mantendo apenas uma cópia. A duplicidade deve ser verificada usando hash (md5 ou sha256), não apenas o nome do arquivo. Inclua uma opção para listar os duplicados sem apagar.',
    category: 'file',
  },
  {
    id: 'sync-directories',
    nameKey: 'template_syncDirectories_name',
    descriptionKey: 'template_syncDirectories_desc',
    prompt: 'Crie um script que sincroniza o conteúdo de um diretório de origem para um de destino, similar a um `rsync -av`. O script deve copiar apenas arquivos novos ou modificados e remover arquivos do destino que não existem mais na origem. Adicione logging detalhado.',
    category: 'file',
  },
  {
    id: 'archive-old-logs',
    nameKey: 'template_archiveOldLogs_name',
    descriptionKey: 'template_archiveOldLogs_desc',
    prompt: 'Gere um script robusto que arquiva e comprime arquivos de log antigos. O script deve:\n1.  Aceitar o diretório de origem dos logs via flag `--log-dir`. Se não for fornecido, usar `/var/log` como padrão.\n2.  Aceitar o diretório de destino para os arquivos arquivados via flag `--error-dir` (o nome da flag deve ser exatamente este). Se não for fornecido, usar um subdiretório chamado `archives` dentro do diretório de logs (ex: `/var/log/archives`).\n3.  Incluir uma função para processar os argumentos de linha de comando.\n4.  Procurar por arquivos que terminam em `.log` no diretório de logs.\n5.  Compactar (usando gzip) qualquer arquivo de log com data de modificação superior a 7 dias.\n6.  Mover os arquivos `.gz` resultantes para o diretório de destino.\n7.  No diretório de destino, procurar e apagar arquivos `.gz` com data de modificação superior a 90 dias.\n8.  Incluir uma função de ajuda (`--help`) que explique como usar o script e suas opções.\n9.  Adicionar tratamento de erros, como verificar se os diretórios existem.',
    category: 'file',
  },
  {
    id: 'process-csv',
    nameKey: 'template_processCsv_name',
    descriptionKey: 'template_processCsv_desc',
    prompt: 'Escreva um script que processa um arquivo CSV. Ele deve aceitar o nome do arquivo e o número de uma coluna como argumentos. O script deve ler o CSV, ignorar o cabeçalho e calcular a soma de todos os valores na coluna especificada. Lide com possíveis erros de formatação.',
    category: 'file',
  },
  {
    id: 'extract-text-pdf',
    nameKey: 'template_extractTextPdf_name',
    descriptionKey: 'template_extractTextPdf_desc',
    prompt: 'Crie um script que extrai texto de todos os arquivos PDF em um diretório. O script deve usar uma ferramenta de linha de comando como `pdftotext` (parte do poppler-utils) e salvar o texto extraído em um arquivo .txt correspondente para cada PDF. Verifique se a dependência está instalada.',
    category: 'file',
  },
  {
    id: 'organize-photos-by-date',
    nameKey: 'template_organizePhotosByDate_name',
    descriptionKey: 'template_organizePhotosByDate_desc',
    prompt: 'Gere um script que organiza arquivos de imagem (JPG, PNG) em subdiretórios por ano e mês. O script deve ler os metadados EXIF da data de captura da foto e mover o arquivo para uma estrutura como `YYYY/MM/`. Se os dados EXIF não existirem, use a data de modificação do arquivo.',
    category: 'file',
  },
  // --- System & Process Management ---
  {
    id: 'disk-space-alert',
    nameKey: 'template_diskSpace_name',
    descriptionKey: 'template_diskSpace_desc',
    prompt: 'Gere um script que monitora o uso do disco da partição raiz (/). O script deve: aceitar um limite de porcentagem como argumento opcional (padrão 85%); se o uso do disco exceder o limite, imprimir um alerta de AVISO formatado em JSON para stdout que inclua o dispositivo, o percentual de uso e o limite excedido; ser compatível com Linux e macOS.',
    category: 'system',
  },
  {
    id: 'system-info-report',
    nameKey: 'template_systemInfoReport_name',
    descriptionKey: 'template_systemInfoReport_desc',
    prompt: 'Crie um script que gera um relatório de informações do sistema. O relatório deve incluir: nome do host, versão do SO, tempo de atividade (uptime), uso de CPU (média de 1 min), uso de memória RAM (total, usada, livre) e os 5 processos que mais consomem memória.',
    category: 'system',
  },
  {
    id: 'auto-update',
    nameKey: 'template_autoUpdate_name',
    descriptionKey: 'template_autoUpdate_desc',
    prompt: 'Escreva um script para automatizar a atualização de pacotes do sistema. O script deve detectar se o sistema usa `apt` (Debian/Ubuntu) ou `yum`/`dnf` (CentOS/Fedora) e executar os comandos de atualização apropriados. O script deve ser executado com privilégios de root e registrar a saída em um arquivo de log.',
    category: 'system',
  },
  {
    id: 'check-service-status',
    nameKey: 'template_checkServiceStatus_name',
    descriptionKey: 'template_checkServiceStatus_desc',
    prompt: 'Gere um script que verifica o status de um serviço do systemd (ex: nginx, sshd). Se o serviço não estiver ativo, o script deve tentar reiniciá-lo e então verificar o status novamente. Envie uma notificação (um simples echo por enquanto) se a reinicialização falhar.',
    category: 'system',
  },
  {
    id: 'manage-users',
    nameKey: 'template_manageUsers_name',
    descriptionKey: 'template_manageUsers_desc',
    prompt: 'Crie um script de gerenciamento de usuários. Ele deve aceitar ações como `--add`, `--delete`, `--list` e um nome de usuário. Para `--add`, ele cria o usuário com um diretório home. Para `--delete`, ele remove o usuário e seu diretório home. Para `--list`, ele lista todos os usuários não-sistema.',
    category: 'system',
  },
  {
    id: 'monitor-logins',
    nameKey: 'template_monitorLogins_name',
    descriptionKey: 'template_monitorLogins_desc',
    prompt: 'Escreva um script que monitore tentativas de login malsucedidas no sistema (ex: via SSH). O script deve analisar o log de autenticação (`/var/log/auth.log` ou similar) e reportar qualquer endereço IP que tenha mais de 5 tentativas falhas na última hora.',
    category: 'system',
  },
  {
    id: 'find-zombie-processes',
    nameKey: 'template_findZombieProcesses_name',
    descriptionKey: 'template_findZombieProcesses_desc',
    prompt: 'Crie um script que procura por processos zumbi no sistema. Se algum processo zumbi for encontrado, o script deve listar o PID do processo zumbi e o PID de seu processo pai. Inclua uma explicação sobre o que são processos zumbi e como eles geralmente são resolvidos.',
    category: 'system',
  },
  {
    id: 'setup-cron-job',
    nameKey: 'template_setupCronJob_name',
    descriptionKey: 'template_setupCronJob_desc',
    prompt: 'Gere um script que adiciona um novo trabalho cron de forma programática. O script deve aceitar a programação (ex: "0 2 * * *") e o comando a ser executado como argumentos. Ele deve verificar se o mesmo comando já existe na crontab para evitar duplicação.',
    category: 'system',
  },
  {
    id: 'list-installed-packages',
    nameKey: 'template_listInstalledPackages_name',
    descriptionKey: 'template_listInstalledPackages_desc',
    prompt: 'Crie um script que lista todos os pacotes instalados pelo usuário e salva a lista em um arquivo de texto. O script deve detectar o gerenciador de pacotes (apt, yum/dnf, pacman, brew) e usar o comando apropriado para listar os pacotes instalados explicitamente.',
    category: 'system',
  },
  {
    id: 'check-high-memory-procs',
    nameKey: 'template_checkHighMemoryProcs_name',
    descriptionKey: 'template_checkHighMemoryProcs_desc',
    prompt: 'Escreva um script que lista os 10 processos que mais consomem memória RAM no sistema. A saída deve ser bem formatada, mostrando o PID, o usuário, o percentual de uso de memória (%MEM) e o comando.',
    category: 'system',
  },
  // --- Network & Web ---
  {
    id: 'check-open-ports',
    nameKey: 'template_portScan_name',
    descriptionKey: 'template_portScan_desc',
    prompt: 'Escreva um script que verifica quais portas estão abertas em um host. O script deve: aceitar um nome de host ou endereço IP como primeiro argumento; aceitar uma lista de portas separadas por vírgula como segundo argumento (ex: 80,443,8080); usar `nc` (netcat) com um timeout curto para verificar cada porta; imprimir uma lista clara de portas abertas e fechadas.',
    category: 'network',
  },
  {
    id: 'check-website-status',
    nameKey: 'template_checkWebsiteStatus_name',
    descriptionKey: 'template_checkWebsiteStatus_desc',
    prompt: 'Gere um script que verifica se uma lista de websites está online. O script deve ler as URLs de um arquivo de texto (um por linha), usar `curl` para checar o código de status HTTP e registrar se cada site está "UP" (status 2xx ou 3xx) ou "DOWN" (outros status ou falha na conexão).',
    category: 'network',
  },
  {
    id: 'measure-download-speed',
    nameKey: 'template_measureDownloadSpeed_name',
    descriptionKey: 'template_measureDownloadSpeed_desc',
    prompt: 'Crie um script que mede a velocidade de download da internet. O script deve baixar um arquivo de teste de um tamanho conhecido (ex: 100MB) usando `curl` ou `wget`, calcular a velocidade em Megabits por segundo (Mbps) e exibir o resultado.',
    category: 'network',
  },
  {
    id: 'get-public-ip',
    nameKey: 'template_getPublicIp_name',
    descriptionKey: 'template_getPublicIp_desc',
    prompt: 'Escreva um script simples que obtém o endereço IP público da máquina usando um serviço externo como `ifconfig.me`, `icanhazip.com` ou `api.ipify.org` através do `curl`. O script deve ter fallbacks para tentar mais de um serviço se o primeiro falhar.',
    category: 'network',
  },
  {
    id: 'basic-firewall-setup',
    nameKey: 'template_basicFirewallSetup_name',
    descriptionKey: 'template_basicFirewallSetup_desc',
    prompt: 'Gere um script de configuração de firewall básico para um servidor Linux usando `ufw`. O script deve: negar todas as conexões de entrada por padrão, permitir todas as de saída, e abrir portas específicas para SSH (22), HTTP (80) e HTTPS (443). O script deve pedir confirmação antes de aplicar as regras.',
    category: 'network',
  },
  {
    id: 'scan-local-network',
    nameKey: 'template_scanLocalNetwork_name',
    descriptionKey: 'template_scanLocalNetwork_desc',
    prompt: 'Crie um script que escaneia a rede local em busca de dispositivos ativos. O script deve determinar o endereço IP e a máscara de sub-rede da máquina local e então usar `nmap` ou um loop com `ping` para encontrar todos os hosts ativos na sub-rede. Exiba uma lista de IPs ativos.',
    category: 'network',
  },
  {
    id: 'dns-lookup',
    nameKey: 'template_dnsLookup_name',
    descriptionKey: 'template_dnsLookup_desc',
    prompt: 'Escreva um script que realiza consultas DNS para um domínio. O script deve aceitar um nome de domínio e um tipo de registro opcional (A, MX, CNAME, TXT). Ele deve usar o comando `dig` e formatar a saída para mostrar apenas as informações mais relevantes da resposta.',
    category: 'network',
  },
  {
    id: 'download-with-retry',
    nameKey: 'template_downloadWithRetry_name',
    descriptionKey: 'template_downloadWithRetry_desc',
    prompt: 'Crie um script que baixa um arquivo de uma URL com lógica de repetição. O script deve aceitar a URL e o nome do arquivo de saída. Ele deve tentar baixar o arquivo até 3 vezes com um intervalo de 10 segundos entre as tentativas se o download falhar, usando `wget` ou `curl`.',
    category: 'network',
  },
  {
    id: 'fetch-weather-api',
    nameKey: 'template_fetchWeatherApi_name',
    descriptionKey: 'template_fetchWeatherApi_desc',
    prompt: 'Gere um script que busca a previsão do tempo para uma cidade usando uma API pública gratuita (como a do OpenWeatherMap, mas use um endpoint de exemplo genérico). O script deve usar `curl` para fazer a requisição e `jq` para extrair e exibir a temperatura e a descrição do tempo a partir da resposta JSON.',
    category: 'network',
  },
  {
    id: 'ssh-wrapper',
    nameKey: 'template_sshWrapper_name',
    descriptionKey: 'template_sshWrapper_desc',
    prompt: 'Crie um script wrapper de SSH que facilita a conexão a uma lista de hosts predefinidos. O script deve ter uma lista de apelidos e hosts correspondentes (ex: "servidor-web" -> "user@1.2.3.4"). Ao executar `./connect.sh servidor-web`, ele deve iniciar a sessão SSH. Adicione um menu interativo se nenhum argumento for fornecido.',
    category: 'network',
  },
  // --- API & Webhooks Templates ---
  {
    id: 'api-get-test',
    nameKey: 'template_getTest_name',
    descriptionKey: 'template_getTest_desc',
    prompt: 'Crie um script que aceita uma URL como argumento. Ele deve usar `curl` para fazer uma requisição GET para essa URL. O script deve verificar se o código de status HTTP da resposta é 200. Se for, deve imprimir "SUCESSO: Endpoint está online (Status 200)". Caso contrário, deve imprimir "FALHA: Endpoint retornou status [código]" e sair com código de erro 1.',
    category: 'api',
  },
  {
    id: 'api-post-json',
    nameKey: 'template_postJson_name',
    descriptionKey: 'template_postJson_desc',
    prompt: 'Gere um script que envia dados JSON para um endpoint de API. O script deve: aceitar a URL do endpoint como argumento; definir um payload JSON fixo dentro do script (ex: `{"name":"novo-item", "quantity": 10}`); usar `curl` para fazer uma requisição POST com o cabeçalho `Content-Type: application/json`; imprimir a resposta completa da API.',
    category: 'api',
  },
  {
    id: 'api-webhook-listener',
    nameKey: 'template_webhookListener_name',
    descriptionKey: 'template_webhookListener_desc',
    prompt: 'Crie um script de ouvinte de webhook. Ele deve: aceitar um número de porta como argumento (padrão 8080); usar `netcat` (nc) em um loop infinito para escutar por conexões nessa porta; para cada requisição recebida, registrar o corpo da requisição em um arquivo de log (`webhook_payloads.log`) com um timestamp.',
    category: 'api',
  },
  {
    id: 'api-parse-json',
    nameKey: 'template_parseJson_name',
    descriptionKey: 'template_parseJson_desc',
    prompt: 'Escreva um script que busca dados de uma API JSON e os processa. O script deve: aceitar uma URL de uma API que retorna um array de objetos JSON; usar `curl` para buscar os dados; usar `jq` para extrair e imprimir o valor de um campo específico (ex: "name") de cada objeto no array. Verifique se `jq` está instalado.',
    category: 'api',
  },
  {
    id: 'api-bearer-auth',
    nameKey: 'template_bearerAuth_name',
    descriptionKey: 'template_bearerAuth_desc',
    prompt: 'Gere um script que demonstre como fazer uma requisição de API autenticada. O script deve: ler uma URL e um token de autenticação (Bearer Token) de variáveis de ambiente (`API_URL` e `API_TOKEN`); usar `curl` para fazer uma requisição GET, passando o token no cabeçalho `Authorization: Bearer $API_TOKEN`; imprimir a resposta da API.',
    category: 'api',
  },
  {
    id: 'api-send-webhook',
    nameKey: 'template_sendWebhook_name',
    descriptionKey: 'template_sendWebhook_desc',
    prompt: 'Crie um script para enviar um payload de webhook. O script deve aceitar uma URL de webhook como argumento. Ele deve enviar um payload JSON de exemplo (ex: `{"event": "test", "user_id": 123}`) para a URL usando `curl` com o método POST e o cabeçalho de `Content-Type` apropriado.',
    category: 'api',
  },
  { id: 'put-request', nameKey: 'template_put_request_name', descriptionKey: 'template_put_request_desc', prompt: 'Gere um script que usa curl para enviar uma requisição PUT para atualizar completamente um recurso em uma API, enviando um payload JSON.', category: 'api' },
  { id: 'patch-request', nameKey: 'template_patch_request_name', descriptionKey: 'template_patch_request_desc', prompt: 'Gere um script que usa curl para enviar uma requisição PATCH para atualizar parcialmente um recurso, enviando apenas os campos a serem alterados em um payload JSON.', category: 'api' },
  { id: 'delete-request', nameKey: 'template_delete_request_name', descriptionKey: 'template_delete_request_desc', prompt: 'Gere um script que usa curl para enviar uma requisição DELETE para remover um recurso específico em uma API e verifica se a resposta é 204 No Content.', category: 'api' },
  { id: 'head-request', nameKey: 'template_head_request_name', descriptionKey: 'template_head_request_desc', prompt: 'Gere um script que usa curl para enviar uma requisição HEAD para obter apenas os cabeçalhos de uma URL, útil para verificar metadados como Content-Type sem baixar o corpo.', category: 'api' },
  { id: 'basic-auth', nameKey: 'template_basic_auth_name', descriptionKey: 'template_basic_auth_desc', prompt: 'Gere um script que faz uma requisição curl para um endpoint protegido por Autenticação Básica (Basic Auth), lendo usuário e senha de variáveis de ambiente.', category: 'api' },
  { id: 'apikey-header', nameKey: 'template_apikey_header_name', descriptionKey: 'template_apikey_header_desc', prompt: 'Gere um script que faz uma requisição curl autenticada passando uma chave de API em um cabeçalho HTTP personalizado, como `X-API-Key`.', category: 'api' },
  { id: 'apikey-query', nameKey: 'template_apikey_query_name', descriptionKey: 'template_apikey_query_desc', prompt: 'Gere um script que faz uma requisição curl autenticada passando uma chave de API como um parâmetro de query na URL (ex: `?apiKey=...`).', category: 'api' },
  { id: 'send-form-data', nameKey: 'template_send_form_name', descriptionKey: 'template_send_form_desc', prompt: 'Gere um script que simula o envio de um formulário web usando curl com o método POST e dados `application/x-www-form-urlencoded`.', category: 'api' },
  { id: 'upload-file', nameKey: 'template_upload_file_name', descriptionKey: 'template_upload_file_desc', prompt: 'Gere um script que faz o upload de um arquivo para um servidor usando curl com `multipart/form-data`, incluindo campos de formulário adicionais.', category: 'api' },
  { id: 'download-file', nameKey: 'template_download_file_name', descriptionKey: 'template_download_file_desc', prompt: 'Gere um script que usa curl para baixar um arquivo binário (como uma imagem ou zip) de uma URL e o salva em disco com o nome original.', category: 'api' },
  { id: 'check-404', nameKey: 'template_check_404_name', descriptionKey: 'template_check_404_desc', prompt: 'Gere um script que testa um endpoint de API para um recurso que não existe e verifica se a resposta HTTP é exatamente 404 (Not Found).', category: 'api' },
  { id: 'check-json-value', nameKey: 'template_check_json_value_name', descriptionKey: 'template_check_json_value_desc', prompt: 'Gere um script que faz uma requisição a uma API, recebe uma resposta JSON e usa `jq` para verificar se um campo específico contém um valor esperado.', category: 'api' },
  { id: 'check-header', nameKey: 'template_check_header_name', descriptionKey: 'template_check_header_desc', prompt: 'Gere um script que faz uma requisição e verifica se um cabeçalho específico (ex: `Content-Type`) na resposta corresponde a um valor esperado (ex: `application/json`).', category: 'api' },
  { id: 'save-response', nameKey: 'template_save_response_name', descriptionKey: 'template_save_response_desc', prompt: 'Gere um script que faz uma requisição de API e salva o corpo da resposta em um arquivo de log com um timestamp no nome.', category: 'api' },
  { id: 'measure-time', nameKey: 'template_measure_time_name', descriptionKey: 'template_measure_time_desc', prompt: 'Gere um script que usa a opção `-w` ou `--write-out` do curl para medir e exibir o tempo total de uma transação de API, incluindo DNS, conexão e transferência.', category: 'api' },
  { id: 'follow-redirects', nameKey: 'template_follow_redirects_name', descriptionKey: 'template_follow_redirects_desc', prompt: 'Gere um script que usa a flag `-L` do curl para seguir automaticamente redirecionamentos HTTP (3xx) e exibir a resposta final.', category: 'api' },
  { id: 'set-timeout', nameKey: 'template_set_timeout_name', descriptionKey: 'template_set_timeout_desc', prompt: 'Gere um script que usa a opção `--max-time` do curl para definir um timeout (ex: 5 segundos) e lida com o erro se a requisição exceder esse tempo.', category: 'api' },
  { id: 'verbose-output', nameKey: 'template_verbose_output_name', descriptionKey: 'template_verbose_output_desc', prompt: 'Gere um script que executa uma requisição curl com a flag `-v` para obter uma saída detalhada de todo o processo de requisição/resposta, útil para depuração.', category: 'api' },
  { id: 'use-proxy', nameKey: 'template_use_proxy_name', descriptionKey: 'template_use_proxy_desc', prompt: 'Gere um script que faz uma requisição de API passando por um servidor proxy, lendo o endereço do proxy de uma variável de ambiente.', category: 'api' },
  { id: 'custom-user-agent', nameKey: 'template_custom_user_agent_name', descriptionKey: 'template_custom_user_agent_desc', prompt: 'Gere um script que define uma string de User-Agent personalizada em uma requisição curl usando a opção `-A`.', category: 'api' },
  { id: 'test-pagination', nameKey: 'template_test_pagination_name', descriptionKey: 'template_test_pagination_desc', prompt: 'Gere um script para testar a paginação de uma API. Ele deve buscar a primeira página, extrair o link da "próxima página" do corpo da resposta JSON e exibi-lo.', category: 'api' },
  { id: 'rate-limit-check', nameKey: 'template_rate_limit_check_name', descriptionKey: 'template_rate_limit_check_desc', prompt: 'Gere um script que faz uma requisição e exibe os cabeçalhos de limite de requisições da resposta (ex: `X-RateLimit-Limit`, `X-RateLimit-Remaining`).', category: 'api' },
  { id: 'health-check', nameKey: 'template_health_check_name', descriptionKey: 'template_health_check_desc', prompt: 'Gere um script de monitoramento que verifica um endpoint de health check (ex: /healthz) em um loop e relata se o serviço está indisponível.', category: 'api' },
  { id: 'graphql-query', nameKey: 'template_graphql_query_name', descriptionKey: 'template_graphql_query_desc', prompt: 'Gere um script que envia uma consulta GraphQL para um endpoint usando curl, passando a query no corpo de uma requisição POST.', category: 'api' },
  { id: 'graphql-variables', nameKey: 'template_graphql_variables_name', descriptionKey: 'template_graphql_variables_desc', prompt: 'Gere um script que envia uma consulta GraphQL com variáveis para um endpoint, passando a query e as variáveis em um payload JSON.', category: 'api' },
  { id: 'listener-log', nameKey: 'template_listener_log_name', descriptionKey: 'template_listener_log_desc', prompt: 'Gere um script de ouvinte de webhook que usa `nc` e `tee` para exibir o payload recebido no terminal e, ao mesmo tempo, adicioná-lo a um arquivo de log.', category: 'api' },
  { id: 'send-hmac', nameKey: 'template_send_hmac_name', descriptionKey: 'template_send_hmac_desc', prompt: 'Gere um script que cria uma assinatura HMAC-SHA256 para um payload JSON e a envia em um cabeçalho personalizado (ex: `X-Webhook-Signature`) junto com o payload.', category: 'api' },
  { id: 'test-receiver', nameKey: 'template_test_receiver_name', descriptionKey: 'template_test_receiver_desc', prompt: 'Gere um script de receptor de webhook que lê o payload, calcula a assinatura HMAC e a compara com a assinatura recebida no cabeçalho para validação.', category: 'api' },
  { id: 'check-github-user', nameKey: 'template_check_github_user_name', descriptionKey: 'template_check_github_user_desc', prompt: 'Gere um script que usa a API pública do GitHub para buscar e exibir informações de um usuário específico, extraindo o nome e o número de repositórios.', category: 'api' },
  { id: 'post-slack', nameKey: 'template_post_slack_name', descriptionKey: 'template_post_slack_desc', prompt: 'Gere um script que envia uma mensagem formatada para um canal do Slack usando um Incoming Webhook URL, lendo a URL de uma variável de ambiente.', category: 'api' },
  { id: 'dns-api', nameKey: 'template_dns_api_name', descriptionKey: 'template_dns_api_desc', prompt: 'Gere um script que usa uma API pública de DNS sobre HTTPS (ex: Google) para obter os registros A de um domínio e exibi-los.', category: 'api' },
  { id: 'url-shortener-api', nameKey: 'template_url_shortener_api_name', descriptionKey: 'template_url_shortener_api_desc', prompt: 'Gere um script que usa uma API pública de encurtamento de URL para encurtar uma URL longa fornecida como argumento.', category: 'api' },
  { id: 'loop-requests', nameKey: 'template_loop_requests_name', descriptionKey: 'template_loop_requests_desc', prompt: 'Gere um script que executa 10 requisições GET em um loop para um endpoint, útil para testes simples de carga ou para verificar a consistência da resposta.', category: 'api' },
  { id: 'chain-requests', nameKey: 'template_chain_requests_name', descriptionKey: 'template_chain_requests_desc', prompt: 'Gere um script que faz uma requisição POST para criar um recurso, extrai o ID da resposta e usa esse ID para fazer uma requisição GET para buscar o recurso recém-criado.', category: 'api' },
  // --- Utilities & Miscellaneous ---
  {
    id: 'password-generator',
    nameKey: 'template_passwordGenerator_name',
    descriptionKey: 'template_passwordGenerator_desc',
    prompt: 'Gere um script que cria senhas aleatórias seguras. O script deve aceitar um argumento para o comprimento da senha (padrão 16). Ele deve incluir uma mistura de letras maiúsculas, minúsculas, números e símbolos. Use `/dev/urandom` para uma melhor aleatoriedade.',
    category: 'utility',
  },
  {
    id: 'todo-cli',
    nameKey: 'template_todoCli_name',
    descriptionKey: 'template_todoCli_desc',
    prompt: 'Crie uma ferramenta de lista de tarefas (todo) de linha de comando. O script deve suportar comandos como `add "Nova tarefa"`, `list`, `done <número>`, e `clear`. As tarefas devem ser salvas em um arquivo de texto no diretório home do usuário.',
    category: 'utility',
  },
  {
    id: 'markdown-to-html',
    nameKey: 'template_markdownToHtml_name',
    descriptionKey: 'template_markdownToHtml_desc',
    prompt: 'Escreva um script que converte um arquivo Markdown em HTML. O script deve usar uma ferramenta como `pandoc` ou `lowdown`. Ele deve aceitar o arquivo de entrada .md e um nome de arquivo de saída .html opcional. Verifique se a dependência (pandoc) está instalada.',
    category: 'utility',
  },
  {
    id: 'screenshot-tool',
    nameKey: 'template_screenshotTool_name',
    descriptionKey: 'template_screenshotTool_desc',
    prompt: 'Crie um script que tira uma captura de tela. O script deve ser compatível com macOS (`screencapture`) e Linux (`maim` ou `scrot`). Ele deve salvar a captura de tela na Área de Trabalho com um nome de arquivo baseado em data e hora. Adicione uma opção de atraso de 5 segundos.',
    category: 'utility',
  },
  {
    id: 'qr-code-generator',
    nameKey: 'template_qrCodeGenerator_name',
    descriptionKey: 'template_qrCodeGenerator_desc',
    prompt: 'Gere um script que cria um código QR a partir de um texto ou URL. O script deve usar a ferramenta `qrencode`. Ele deve aceitar o texto como argumento e salvar o código QR como um arquivo de imagem PNG. Verifique se o `qrencode` está instalado.',
    category: 'utility',
  },
  {
    id: 'timer-stopwatch',
    nameKey: 'template_timerStopwatch_name',
    descriptionKey: 'template_timerStopwatch_desc',
    prompt: 'Crie um script de timer/cronômetro para o terminal. Ele deve aceitar um tempo em segundos (ex: `timer.sh 60`) e fazer uma contagem regressiva, atualizando a mesma linha. Ao final, deve emitir um som de alerta (usando o caractere de sino `\a`).',
    category: 'utility',
  },
  {
    id: 'extract-audio-from-video',
    nameKey: 'template_extractAudioFromVideo_name',
    descriptionKey: 'template_extractAudioFromVideo_desc',
    prompt: 'Escreva um script que extrai a faixa de áudio de um arquivo de vídeo e a salva como MP3. O script deve usar `ffmpeg`. Ele deve aceitar o nome do arquivo de vídeo de entrada e, opcionalmente, o nome do arquivo de áudio de saída. Verifique se `ffmpeg` está instalado.',
    category: 'utility',
  },
  {
    id: 'url-shortener-cli',
    nameKey: 'template_urlShortenerCli_name',
    descriptionKey: 'template_urlShortenerCli_desc',
    prompt: 'Crie uma ferramenta de linha de comando que encurta uma URL longa usando um serviço público de encurtamento (como `tinyurl.com` ou um similar que não exija API key). O script deve aceitar a URL longa como argumento e imprimir a URL curta resultante.',
    category: 'utility',
  },
  {
    id: 'simple-calculator',
    nameKey: 'template_simpleCalculator_name',
    descriptionKey: 'template_simpleCalculator_desc',
    prompt: 'Gere um script de calculadora de linha de comando que avalia uma expressão matemática fornecida como argumento. O script deve suportar adição, subtração, multiplicação e divisão. Use `bc` ou avaliação aritmética do Bash para os cálculos. Lide com a divisão por zero.',
    category: 'utility',
  },
  {
    id: 'get-random-quote',
    nameKey: 'template_getRandomQuote_name',
    descriptionKey: 'template_getRandomQuote_desc',
    prompt: 'Escreva um script que busca uma citação aleatória de uma API pública (como `https://api.quotable.io/random`) usando `curl` e `jq`. O script deve extrair a citação e o autor do JSON e exibi-los em um formato agradável no terminal.',
    category: 'utility',
  },
];